/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R403RouteImport } from './routes/403'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CoursesSlugIndexRouteImport } from './routes/courses.$slug.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as CoursesSlugBuyRouteImport } from './routes/courses.$slug.buy'
import { Route as AuthenticatedLearnCourseSlugRouteImport } from './routes/_authenticated/learn.$courseSlug'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedLearnCourseSlugLessonSlugRouteImport } from './routes/_authenticated/learn.$courseSlug.$lessonSlug'
import { Route as AuthenticatedAdminEditPageRouteImport } from './routes/_authenticated/admin.edit.$page'
import { Route as AuthenticatedAdminCoursesNewRouteImport } from './routes/_authenticated/admin.courses.new'
import { Route as AuthenticatedAdminContentPageRouteImport } from './routes/_authenticated/admin.content.$page'
import { Route as AuthenticatedAdminCoursesIdEditRouteImport } from './routes/_authenticated/admin.courses.$id.edit'
import { Route as AuthenticatedAdminCoursesCourseIdLessonsIndexRouteImport } from './routes/_authenticated/admin.courses.$courseId.lessons.index'
import { Route as AuthenticatedAdminCoursesCourseIdLessonsNewRouteImport } from './routes/_authenticated/admin.courses.$courseId.lessons.new'
import { Route as AuthenticatedAdminCoursesCourseIdLessonsLessonIdEditRouteImport } from './routes/_authenticated/admin.courses.$courseId.lessons.$lessonId.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CoursesSlugIndexRoute = CoursesSlugIndexRouteImport.update({
  id: '/courses/$slug/',
  path: '/courses/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const CoursesSlugBuyRoute = CoursesSlugBuyRouteImport.update({
  id: '/courses/$slug/buy',
  path: '/courses/$slug/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLearnCourseSlugRoute =
  AuthenticatedLearnCourseSlugRouteImport.update({
    id: '/learn/$courseSlug',
    path: '/learn/$courseSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedLearnCourseSlugLessonSlugRoute =
  AuthenticatedLearnCourseSlugLessonSlugRouteImport.update({
    id: '/$lessonSlug',
    path: '/$lessonSlug',
    getParentRoute: () => AuthenticatedLearnCourseSlugRoute,
  } as any)
const AuthenticatedAdminEditPageRoute =
  AuthenticatedAdminEditPageRouteImport.update({
    id: '/edit/$page',
    path: '/edit/$page',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesNewRoute =
  AuthenticatedAdminCoursesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)
const AuthenticatedAdminContentPageRoute =
  AuthenticatedAdminContentPageRouteImport.update({
    id: '/$page',
    path: '/$page',
    getParentRoute: () => AuthenticatedAdminContentRoute,
  } as any)
const AuthenticatedAdminCoursesIdEditRoute =
  AuthenticatedAdminCoursesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)
const AuthenticatedAdminCoursesCourseIdLessonsIndexRoute =
  AuthenticatedAdminCoursesCourseIdLessonsIndexRouteImport.update({
    id: '/$courseId/lessons/',
    path: '/$courseId/lessons/',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)
const AuthenticatedAdminCoursesCourseIdLessonsNewRoute =
  AuthenticatedAdminCoursesCourseIdLessonsNewRouteImport.update({
    id: '/$courseId/lessons/new',
    path: '/$courseId/lessons/new',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)
const AuthenticatedAdminCoursesCourseIdLessonsLessonIdEditRoute =
  AuthenticatedAdminCoursesCourseIdLessonsLessonIdEditRouteImport.update({
    id: '/$courseId/lessons/$lessonId/edit',
    path: '/$courseId/lessons/$lessonId/edit',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/content': typeof AuthenticatedAdminContentRouteWithChildren
  '/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/learn/$courseSlug': typeof AuthenticatedLearnCourseSlugRouteWithChildren
  '/courses/$slug/buy': typeof CoursesSlugBuyRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
  '/admin/content/$page': typeof AuthenticatedAdminContentPageRoute
  '/admin/courses/new': typeof AuthenticatedAdminCoursesNewRoute
  '/admin/edit/$page': typeof AuthenticatedAdminEditPageRoute
  '/learn/$courseSlug/$lessonSlug': typeof AuthenticatedLearnCourseSlugLessonSlugRoute
  '/admin/courses/$id/edit': typeof AuthenticatedAdminCoursesIdEditRoute
  '/admin/courses/$courseId/lessons/new': typeof AuthenticatedAdminCoursesCourseIdLessonsNewRoute
  '/admin/courses/$courseId/lessons/': typeof AuthenticatedAdminCoursesCourseIdLessonsIndexRoute
  '/admin/courses/$courseId/lessons/$lessonId/edit': typeof AuthenticatedAdminCoursesCourseIdLessonsLessonIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/content': typeof AuthenticatedAdminContentRouteWithChildren
  '/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/learn/$courseSlug': typeof AuthenticatedLearnCourseSlugRouteWithChildren
  '/courses/$slug/buy': typeof CoursesSlugBuyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/courses/$slug': typeof CoursesSlugIndexRoute
  '/admin/content/$page': typeof AuthenticatedAdminContentPageRoute
  '/admin/courses/new': typeof AuthenticatedAdminCoursesNewRoute
  '/admin/edit/$page': typeof AuthenticatedAdminEditPageRoute
  '/learn/$courseSlug/$lessonSlug': typeof AuthenticatedLearnCourseSlugLessonSlugRoute
  '/admin/courses/$id/edit': typeof AuthenticatedAdminCoursesIdEditRoute
  '/admin/courses/$courseId/lessons/new': typeof AuthenticatedAdminCoursesCourseIdLessonsNewRoute
  '/admin/courses/$courseId/lessons': typeof AuthenticatedAdminCoursesCourseIdLessonsIndexRoute
  '/admin/courses/$courseId/lessons/$lessonId/edit': typeof AuthenticatedAdminCoursesCourseIdLessonsLessonIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/403': typeof R403Route
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRouteWithChildren
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/learn/$courseSlug': typeof AuthenticatedLearnCourseSlugRouteWithChildren
  '/courses/$slug/buy': typeof CoursesSlugBuyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
  '/_authenticated/admin/content/$page': typeof AuthenticatedAdminContentPageRoute
  '/_authenticated/admin/courses/new': typeof AuthenticatedAdminCoursesNewRoute
  '/_authenticated/admin/edit/$page': typeof AuthenticatedAdminEditPageRoute
  '/_authenticated/learn/$courseSlug/$lessonSlug': typeof AuthenticatedLearnCourseSlugLessonSlugRoute
  '/_authenticated/admin/courses/$id/edit': typeof AuthenticatedAdminCoursesIdEditRoute
  '/_authenticated/admin/courses/$courseId/lessons/new': typeof AuthenticatedAdminCoursesCourseIdLessonsNewRoute
  '/_authenticated/admin/courses/$courseId/lessons/': typeof AuthenticatedAdminCoursesCourseIdLessonsIndexRoute
  '/_authenticated/admin/courses/$courseId/lessons/$lessonId/edit': typeof AuthenticatedAdminCoursesCourseIdLessonsLessonIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/about'
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/wishlist'
    | '/courses/'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/payments'
    | '/learn/$courseSlug'
    | '/courses/$slug/buy'
    | '/admin/'
    | '/courses/$slug/'
    | '/admin/content/$page'
    | '/admin/courses/new'
    | '/admin/edit/$page'
    | '/learn/$courseSlug/$lessonSlug'
    | '/admin/courses/$id/edit'
    | '/admin/courses/$courseId/lessons/new'
    | '/admin/courses/$courseId/lessons/'
    | '/admin/courses/$courseId/lessons/$lessonId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/about'
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/dashboard'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/wishlist'
    | '/courses'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/payments'
    | '/learn/$courseSlug'
    | '/courses/$slug/buy'
    | '/admin'
    | '/courses/$slug'
    | '/admin/content/$page'
    | '/admin/courses/new'
    | '/admin/edit/$page'
    | '/learn/$courseSlug/$lessonSlug'
    | '/admin/courses/$id/edit'
    | '/admin/courses/$courseId/lessons/new'
    | '/admin/courses/$courseId/lessons'
    | '/admin/courses/$courseId/lessons/$lessonId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/403'
    | '/about'
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/payments'
    | '/_authenticated/profile'
    | '/_authenticated/wishlist'
    | '/courses/'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/payments'
    | '/_authenticated/learn/$courseSlug'
    | '/courses/$slug/buy'
    | '/_authenticated/admin/'
    | '/courses/$slug/'
    | '/_authenticated/admin/content/$page'
    | '/_authenticated/admin/courses/new'
    | '/_authenticated/admin/edit/$page'
    | '/_authenticated/learn/$courseSlug/$lessonSlug'
    | '/_authenticated/admin/courses/$id/edit'
    | '/_authenticated/admin/courses/$courseId/lessons/new'
    | '/_authenticated/admin/courses/$courseId/lessons/'
    | '/_authenticated/admin/courses/$courseId/lessons/$lessonId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R403Route: typeof R403Route
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  CoursesSlugBuyRoute: typeof CoursesSlugBuyRoute
  CoursesSlugIndexRoute: typeof CoursesSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/courses/$slug/': {
      id: '/courses/$slug/'
      path: '/courses/$slug'
      fullPath: '/courses/$slug/'
      preLoaderRoute: typeof CoursesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/courses/$slug/buy': {
      id: '/courses/$slug/buy'
      path: '/courses/$slug/buy'
      fullPath: '/courses/$slug/buy'
      preLoaderRoute: typeof CoursesSlugBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/learn/$courseSlug': {
      id: '/_authenticated/learn/$courseSlug'
      path: '/learn/$courseSlug'
      fullPath: '/learn/$courseSlug'
      preLoaderRoute: typeof AuthenticatedLearnCourseSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/learn/$courseSlug/$lessonSlug': {
      id: '/_authenticated/learn/$courseSlug/$lessonSlug'
      path: '/$lessonSlug'
      fullPath: '/learn/$courseSlug/$lessonSlug'
      preLoaderRoute: typeof AuthenticatedLearnCourseSlugLessonSlugRouteImport
      parentRoute: typeof AuthenticatedLearnCourseSlugRoute
    }
    '/_authenticated/admin/edit/$page': {
      id: '/_authenticated/admin/edit/$page'
      path: '/edit/$page'
      fullPath: '/admin/edit/$page'
      preLoaderRoute: typeof AuthenticatedAdminEditPageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses/new': {
      id: '/_authenticated/admin/courses/new'
      path: '/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AuthenticatedAdminCoursesNewRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
    '/_authenticated/admin/content/$page': {
      id: '/_authenticated/admin/content/$page'
      path: '/$page'
      fullPath: '/admin/content/$page'
      preLoaderRoute: typeof AuthenticatedAdminContentPageRouteImport
      parentRoute: typeof AuthenticatedAdminContentRoute
    }
    '/_authenticated/admin/courses/$id/edit': {
      id: '/_authenticated/admin/courses/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/courses/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
    '/_authenticated/admin/courses/$courseId/lessons/': {
      id: '/_authenticated/admin/courses/$courseId/lessons/'
      path: '/$courseId/lessons'
      fullPath: '/admin/courses/$courseId/lessons/'
      preLoaderRoute: typeof AuthenticatedAdminCoursesCourseIdLessonsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
    '/_authenticated/admin/courses/$courseId/lessons/new': {
      id: '/_authenticated/admin/courses/$courseId/lessons/new'
      path: '/$courseId/lessons/new'
      fullPath: '/admin/courses/$courseId/lessons/new'
      preLoaderRoute: typeof AuthenticatedAdminCoursesCourseIdLessonsNewRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
    '/_authenticated/admin/courses/$courseId/lessons/$lessonId/edit': {
      id: '/_authenticated/admin/courses/$courseId/lessons/$lessonId/edit'
      path: '/$courseId/lessons/$lessonId/edit'
      fullPath: '/admin/courses/$courseId/lessons/$lessonId/edit'
      preLoaderRoute: typeof AuthenticatedAdminCoursesCourseIdLessonsLessonIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
  }
}

interface AuthenticatedAdminContentRouteChildren {
  AuthenticatedAdminContentPageRoute: typeof AuthenticatedAdminContentPageRoute
}

const AuthenticatedAdminContentRouteChildren: AuthenticatedAdminContentRouteChildren =
  {
    AuthenticatedAdminContentPageRoute: AuthenticatedAdminContentPageRoute,
  }

const AuthenticatedAdminContentRouteWithChildren =
  AuthenticatedAdminContentRoute._addFileChildren(
    AuthenticatedAdminContentRouteChildren,
  )

interface AuthenticatedAdminCoursesRouteChildren {
  AuthenticatedAdminCoursesNewRoute: typeof AuthenticatedAdminCoursesNewRoute
  AuthenticatedAdminCoursesIdEditRoute: typeof AuthenticatedAdminCoursesIdEditRoute
  AuthenticatedAdminCoursesCourseIdLessonsNewRoute: typeof AuthenticatedAdminCoursesCourseIdLessonsNewRoute
  AuthenticatedAdminCoursesCourseIdLessonsIndexRoute: typeof AuthenticatedAdminCoursesCourseIdLessonsIndexRoute
  AuthenticatedAdminCoursesCourseIdLessonsLessonIdEditRoute: typeof AuthenticatedAdminCoursesCourseIdLessonsLessonIdEditRoute
}

const AuthenticatedAdminCoursesRouteChildren: AuthenticatedAdminCoursesRouteChildren =
  {
    AuthenticatedAdminCoursesNewRoute: AuthenticatedAdminCoursesNewRoute,
    AuthenticatedAdminCoursesIdEditRoute: AuthenticatedAdminCoursesIdEditRoute,
    AuthenticatedAdminCoursesCourseIdLessonsNewRoute:
      AuthenticatedAdminCoursesCourseIdLessonsNewRoute,
    AuthenticatedAdminCoursesCourseIdLessonsIndexRoute:
      AuthenticatedAdminCoursesCourseIdLessonsIndexRoute,
    AuthenticatedAdminCoursesCourseIdLessonsLessonIdEditRoute:
      AuthenticatedAdminCoursesCourseIdLessonsLessonIdEditRoute,
  }

const AuthenticatedAdminCoursesRouteWithChildren =
  AuthenticatedAdminCoursesRoute._addFileChildren(
    AuthenticatedAdminCoursesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRouteWithChildren
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRouteWithChildren
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEditPageRoute: typeof AuthenticatedAdminEditPageRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRouteWithChildren,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRouteWithChildren,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEditPageRoute: AuthenticatedAdminEditPageRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedLearnCourseSlugRouteChildren {
  AuthenticatedLearnCourseSlugLessonSlugRoute: typeof AuthenticatedLearnCourseSlugLessonSlugRoute
}

const AuthenticatedLearnCourseSlugRouteChildren: AuthenticatedLearnCourseSlugRouteChildren =
  {
    AuthenticatedLearnCourseSlugLessonSlugRoute:
      AuthenticatedLearnCourseSlugLessonSlugRoute,
  }

const AuthenticatedLearnCourseSlugRouteWithChildren =
  AuthenticatedLearnCourseSlugRoute._addFileChildren(
    AuthenticatedLearnCourseSlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
  AuthenticatedLearnCourseSlugRoute: typeof AuthenticatedLearnCourseSlugRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
  AuthenticatedLearnCourseSlugRoute:
    AuthenticatedLearnCourseSlugRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R403Route: R403Route,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  CoursesSlugBuyRoute: CoursesSlugBuyRoute,
  CoursesSlugIndexRoute: CoursesSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
