// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tonsxmyntprstqzonjmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvbnN4bXludHByc3Rxem9uam1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQzMzU4MTAsImV4cCI6MjA5OTkxMTgxMH0.sp2M7WN1fYvQiQ97rstv3QUPrIkWkEuFfRuzY9NG-Ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});